database:
 host: localhost
 port: 3306
 database: betteralts
 user: root
 password: password
 poolSize: 10
 connectionTimeout: 10000
 idleTimeout: 600000
 maxLifetime: 7200000
altCost:
 diamond:
  material: DIAMOND
  amount: 32
onlineCost:
 emerald:
  material: EMERALD
  amount: 64
altScaleFactor: 2.2 #number of alts ^ scaleFactor cost
onlineScaleFactor: 2.5
