name: BetterAlts
version: ${project.version}
author: [TealNerd]
depend: [CivModCore]
main: com.civclassic.betteralts.BetterAltsBukkit
commands:
  alts:
permissions:
  betteralts.admin:
    default: op